In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect(r"C:\Users\my pc\Desktop\sales.db")

In [3]:
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('sales',)]

In [4]:
query = "SELECT * FROM sales LIMIT 5;"
df = pd.read_sql_query(query, conn)
df

,field1,field2,field3,field4,field5,field6,field7,field8,field9,field10,field11,field12,field13
0,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.96,2,0,41.9136
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.94,3,0,219.582
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.62,2,0,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.031

In [5]:
query = "SELECT field8, field10 FROM sales LIMIT 10;"
df = pd.read_sql_query(query, conn)
df

            field8   field10
0         Category     Sales
1        Furniture    261.96
2        Furniture    731.94
3  Office Supplies     14.62
4        Furniture  957.5775
5  Office Supplies    22.368
6        Furniture     48.86
7  Office Supplies      7.28
8       Technology   907.152
9  Office Supplies    18.504

In [6]:
query = "SELECT * FROM sales WHERE field10 > 1000;"
df = pd.read_sql_query(query, conn)
df

,field1,field2,field3,field4,field5,field6,field7,field8,field9,field10,field11,field12,field13
0,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.96,2,0,41.9136
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.94,3,0,219.582
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.62,2,0,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.031
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9722,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.248,3,0.2,4.1028
9723,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.96,2,0,15.6332
9724,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932
9725,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6,4,0,13.32
9726,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.16,2,0,72.948

In [7]:
query = "SELECT * FROM sales ORDER BY field10 DESC;"
df = pd.read_sql_query(query, conn)
df

,field1,field2,field3,field4,field5,field6,field7,field8,field9,field10,field11,field12,field13
0,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
1,Second Class,Home Office,United States,Indianapolis,Indiana,46203,Central,Technology,Copiers,999.98,2,0,449.991
2,Standard Class,Consumer,United States,Des Moines,Washington,98198,West,Technology,Copiers,999.98,2,0,449.991
3,Second Class,Home Office,United States,Milwaukee,Wisconsin,53209,Central,Technology,Accessories,999.96,4,0,229.9908
4,Standard Class,Consumer,United States,Arlington,Texas,76017,Central,Office Supplies,Storage,999.432,7,0.2,124.929
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,Same Day,Corporate,United States,Mesquite,Texas,75150,Central,Office Supplies,Binders,0.876,1,0.8,-1.4016
9991,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Office Supplies,Binders,0.852,1,0.7,-0.5964
9992,Standard Class,Corporate,United States,Chicago,Illinois,60623,Central,Office Supplies,Binders,0.836,1,0.8,-1.3376
9993,Same Day,Corporate,United States,Waco,Texas,76706,Central,Office Supplies,Binders,0.556,1,0.8,-0.9452
9994,Standard Class,Consumer,United States,Houston,Texas,77095,Central,Office Supplies,Appliances,0.444,1,0.8,-1.11

In [8]:
query = "SELECT AVG(field10) AS Average_Sales FROM sales;"
df = pd.read_sql_query(query, conn)
df

   Average_Sales
0     229.835004

In [9]:
query = "SELECT AVG(field10) AS Average_Sales FROM sales;"
df = pd.read_sql_query(query, conn)
df

   Average_Sales
0     229.835004

In [11]:
conn.close()